### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by arthurwolf** [teunissenstefan/chatgpt-gui#1]
I follow the instructions and get : 

`error: package `gtk4-sys v0.5.5` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.60.0`

I don't know how to fix this. Any help?

Thanks.

**Comment by teunissenstefan** [comment]
Looks like you should update your local Rust installation. How did you install Rust? If you used rustup, you can use `rustup update` to update both Rust and Cargo.

**Comment by arthurwolf** [comment]
I got rustup from https://rustup.rs/

I ran the curl | sh command.

I ran rustup update

I followed the instructions in the Readme.

I get this error:

```
╭─arthur at aquarelle in /ram 23-03-08 - 22:15:49
╰─○ git clone git@github.com:teunissenstefan/chatgpt-gui.git
Cloning into 'chatgpt-gui'...
remote: Enumerating objects: 153, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 153 (delta 78), reused 117 (delta 43), pack-reused 0
Receiving objects: 100% (153/153), 983.22 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (78/78), done.
╭─arthur at aquarelle in /ram 23-03-08 - 22:15:54
╭─arthur at aquarelle in /ram 23-03-08 - 22:15:54
╰─○ cd chatgpt-gui/
╭─arthur at aquarelle in /ram/chatgpt-gui on master✔ 23-03-08 - 22:16:05
╰─⠠⠵ cargo build --release                                                                                                                                                                                                                                                                                                                                                                                                  on master|✔
   Compiling pkg-config v0.3.26
   Compiling serde v1.0.152
   Compiling smallvec v1.10.0
   Compiling heck v0.4.1
   Compiling version-compare v0.1.1
   Compiling proc-macro2 v1.0.50
   Compiling quote v1.0.23
   Compiling autocfg v1.1.0
   Compiling unicode-ident v1.0.6
   Compiling syn v1.0.107
   Compiling libc v0.2.139
   Compiling thiserror v1.0.38
   Compiling version_check v0.9.4
   Compiling cfg-expr v0.11.0
   Compiling memchr v2.5.0
   Compiling futures-core v0.3.26
   Compiling indexmap v1.9.2
   Compiling hashbrown v0.12.3
   Compiling slab v0.4.7
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling futures-task v0.3.26
   Compiling anyhow v1.0.68
   Compiling toml_datetime v0.5.1
   Compiling once_cell v1.17.0
   Compiling futures-util v0.3.26
   Compiling nom8 v0.2.0
   Compiling pin-project-lite v0.2.9
   Compiling pin-utils v0.1.0
   Compiling cc v1.0.79
   Compiling futures-channel v0.3.26
   Compiling bitflags v1.3.2
   Compiling ucd-trie v0.1.5
   Compiling gio v0.16.7
   Compiling futures-io v0.3.26
   Compiling memoffset v0.6.5
   Compiling serde_derive v1.0.152
   Compiling glib-build-tools v0.16.3
   Compiling serde_json v1.0.91
   Compiling curl v0.4.44
   Compiling socket2 v0.4.7
   Compiling chatgpt-gui v0.1.0 (/ram/chatgpt-gui)
   Compiling openssl-probe v0.1.5
   Compiling itoa v1.0.5
   Compiling ryu v1.0.12
   Compiling md5 v0.7.0
   Compiling whoami v1.3.0
error: failed to run custom build command for `chatgpt-gui v0.1.0 (/ram/chatgpt-gui)`

Caused by:
  process didn't exit successfully: `/ram/chatgpt-gui/target/release/build/chatgpt-gui-0b56a3e8efdd1662/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/arthur/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-build-tools-0.16.3/src/lib.rs:30:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
╭─arthur at aquarelle in /ram/chatgpt-gui on master✔ 23-03-08 - 22:16:13

```

Versions:

```
╭─arthur at aquarelle in /ram/chatgpt-gui on master✔ 23-03-08 - 22:18:27
╰─⠠⠵ rustc --version                                                                                                                                                                                                                                                                                                                                                                                                        on master|✔
rustc 1.67.1 (d5a82bbd2 2023-02-07)
╭─arthur at aquarelle in /ram/chatgpt-gui on master✔ 23-03-08 - 22:18:29
╰─⠠⠵ cargo version                                                                                                                                                                                                                                                                                                                                                                                                          on master|✔
cargo 1.67.1 (8ecd4f20a 2023-01-10)
╭─arthur at aquarelle in /ram/chatgpt-gui on master✔ 23-03-08 - 22:18:33
╰─⠠⠵      
```

**Comment by teunissenstefan** [comment]
Do you have glib2 installed? I took a look at `~/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-build-tools-0.16.3/src/lib.rs:30:10` and it's trying to run the `glib-compile-resources` command. Could you try to run the command manually to see if you have it installed? If not, you should install glib2.
